name: Build a single Docker image
on:
  workflow_dispatch:
    inputs:
      name: { default: "", description: name }
  workflow_call:
    inputs:
      name: { type: string, default: "" }

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Building ${{ inputs.name }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - run: ./scripts/build${{ inputs.name }}.sh --test --push
      